spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wechat?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Lvchuang@123
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
  jpa:
    show-sql: true
  application:
    name: order
env:
  cao
girl:
  name: lili
  age: 23
